Warrior lunge/toss nerf
Skyrat-SS13/Skyrat-tgmc-old pull request #98
Opened 2021-06-16 20:42 UTC by BlueHNT

## About The Pull Request
Slight nerf to warrior's lunge and toss

## Why It's Good For The Game
Warrior as of now is "busted" and his lunge and fling play the biggest role in this. Slight nerf to his overly giant lunge {whole viewable surrounding} and fling which has the same fling send off as shrike with added stun.

## Changelog
:cl:
balance: rebalanced something
/:cl:

2021-06-16 23:47 UTC, ZephyrTFA commented on code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> +	X.throw_at(get_step_towards(A, X), 4, 4, X)
```suggestion
	//original: X.throw_at(get_step_towards(A, X), 6, 2, X)
	X.throw_at(get_step_towards(A, X), 4, 4, X) // Skyrat Edit - Warrior Toss Nerf
```

2021-06-16 23:48 UTC, ZephyrTFA commented on code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> +	var/fling_distance = 3
```suggestion
	var/fling_distance = 3 // Skyrat Edit - Warrior Toss Nerf - original: 5
```

2021-06-16 23:48 UTC, ZephyrTFA commented on code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> +	var/stun_duration = 0.5 SECONDS
```suggestion
	var/stun_duration = 0.5 SECONDS // // Skyrat Edit - Warrior Toss Nerf - original: 1 SECONDS
```

2021-06-16 23:49 UTC, ZephyrTFA requested changes
Needs a few changes, in particular it needs to conform to Skyrat Standards.
All the changes that are needed I requested.

2021-06-17 16:07 UTC, BlueHNT commented
> Needs a few changes, in particular it needs to conform to Skyrat Standards.
> All the changes that are needed I requested.

If you're using a github like VSC lense, then it already says that...?

2021-06-17 19:10 UTC, Smudged commented
Good Change, Warrior has perhaps been a liittlee stronger as of late, due to multiple buffs prior back when warrior was.. nerfed to the ground.

This should help in at least one of the problems marines complain about, and it's more reasonable

2021-06-18 12:58 UTC, ZephyrTFA commented
I want to merge this; but you aren't documenting the changes correctly.
Please document the changes correctly.

2021-06-18 14:24 UTC, BlueHNT reviewed
Documentation has been added and commited, awaiting approval

2021-06-18 14:28 UTC, ZephyrTFA approved these changes

2021-06-18 14:29 UTC, merged